dist: trusty
git:
  # use depth 2 just in case two refs get pushed at once (like a tag)
  depth: 2
language: ruby
rvm:
- &release_rvm 2.5.3
- 2.4.5
- 2.3.8
- jruby-9.2.5.0
- jruby-9.1.17.0
script: bundle exec rake spec
notifications:
  email:
    on_success: never
    on_failure: change
deploy:
  provider: rubygems
  gem: jekyll-asciidoc
  api_key: ${RUBYGEMS_API_KEY}
  on:
    tags: true
    repo: asciidoctor/jekyll-asciidoc
    rvm: *release_rvm
