sudo: false
git:
  depth: 1
language: ruby
rvm:
  - &release_rvm 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1.10
  - jruby-9.1.7.0
env:
  - ''
  - JEKYLL_VERSION=2.3.0
matrix:
  exclude:
    - rvm: 2.4.0
      env: JEKYLL_VERSION=2.3.0
    - rvm: jruby-9.1.7.0
      env: JEKYLL_VERSION=2.3.0
script: bundle exec rake spec
notifications:
  email:
    on_success: never
    on_failure: change
deploy:
  on:
    tags: true
    rvm: *release_rvm
  provider: rubygems
  api_key:
    secure: ciClQ+wu4bVkDSIAaFi/dqAmObn+H3VVVPvgSGxcT4liTN54b/UFFgpOewpz4k2NyxMY6qQR7NLnM130WI+ly9yksM/KllJOY4Y+LurPEpY77SoAt2r/1G5R+T7rnlZp3FKsgHTBEHorb6JdQ2xWkr5Z+mIcV1AzSO0rEk/gwGo=
