sudo: false
git:
  depth: 1
language: ruby
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1.10
  - jruby-9.1.7.0
env:
  - ''
  - JEKYLL_VERSION=2.3.0
matrix:
  exclude:
    - rvm: jruby-9.1.7.0
      env: JEKYLL_VERSION=2.3.0
script: bundle exec rake spec
notifications:
  email:
    on_success: never
    on_failure: change
